# Raw data to clean data conversion using python EDA

In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [3]:
emp=pd.read_excel(r"C:\Users\LENOVO\Downloads\Rawdata.xlsx")

In [7]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [4]:
id(emp)

1490779831136

In [5]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='str')

In [6]:
emp.shape #dimension

(6, 6)

In [8]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [9]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [10]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       4 non-null      str
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       5 non-null      str
dtypes: str(6)
memory usage: 619.0 bytes

In [11]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [12]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [13]:
emp.dtypes

Name        str
Domain      str
Age         str
Location    str
Salary      str
Exp         str
dtype: object

# DATA CLEANING OR DATA CLEANSING

In [14]:
emp['Name'] # unclean data (3) speacial char

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: str

In [15]:
emp['Name']=emp['Name'].str.replace(r'\W','',regex=True) # we are using replace function (non word char)

In [16]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: str

In [17]:
emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [18]:
emp['Domain']

0     Datascience#$
1           Testing
2    Dataanalyst^^#
3       Ana^^lytics
4        Statistics
5               NLP
Name: Domain, dtype: str

In [19]:
emp['Domain']=emp['Domain'].str.replace(r'\W','',regex=True)

In [20]:
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: str

In [21]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [22]:
emp['Age']

0    34 years
1      45' yr
2         NaN
3         NaN
4       67-yr
5        55yr
Name: Age, dtype: str

In [23]:
emp['Age']=emp['Age'].str.replace(r'\W','',regex=True)

In [24]:
emp['Age']  # it is not cleaned properly

0    34years
1       45yr
2        NaN
3        NaN
4       67yr
5       55yr
Name: Age, dtype: str

In [25]:
emp['Age']=emp['Age'].str.extract('(\d+)')      #r(r'(\\d+)') if we didn't get ans apply this raw,  here extract function is used

In [26]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: str

In [27]:
emp['Location']=emp['Location'].str.replace(r'\W','',regex=True)

In [28]:
emp['Location']    # it is better to clean all the attributes

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: str

In [30]:
emp['Salary']=emp['Salary'].str.replace(r'\W','',regex=True)

In [31]:
emp['Salary']

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: str

In [33]:
emp['Exp']=emp['Exp'].str.extract('(\d+)')

In [34]:
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: str

In [35]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [36]:
clean_data=emp.copy()

In [37]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

# EDA TECHNIQUES

In [38]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [39]:
clean_data['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: str

In [40]:
import numpy as np

In [41]:
clean_data['Age']=clean_data['Age'].fillna(np.mean(pd.to_numeric(clean_data['Age'])))

In [42]:
clean_data['Age']

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [43]:
clean_data['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: str

In [44]:
clean_data['Exp']=clean_data['Exp'].fillna(np.mean(pd.to_numeric(clean_data['Exp'])))

In [45]:
clean_data['Exp']

0      2
1      3
2      4
3    4.8
4      5
5     10
Name: Exp, dtype: object

In [46]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [47]:
clean_data['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: str

In [49]:
clean_data['Location']=clean_data['Location'].fillna(np.mode(pd.to_numeric(clean_data['Location'])))

AttributeError: module 'numpy' has no attribute 'mode'

In [50]:
clean_data['Location']=clean_data['Location'].fillna(clean_data['Location'].mode()[0])

In [51]:
clean_data['Location']

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: str

In [52]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [53]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      object
 3   Location  6 non-null      str
 4   Salary    6 non-null      str
 5   Exp       6 non-null      object
dtypes: object(2), str(4)
memory usage: 574.0+ bytes

In [54]:
clean_data['Age']=clean_data['Age'].astype(int)

In [55]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      int64
 3   Location  6 non-null      str
 4   Salary    6 non-null      str
 5   Exp       6 non-null      object
dtypes: int64(1), object(1), str(4)
memory usage: 574.0+ bytes

In [56]:
clean_data['Exp']=clean_data['Exp'].astype(int)

In [57]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      int64
 3   Location  6 non-null      str
 4   Salary    6 non-null      str
 5   Exp       6 non-null      int64
dtypes: int64(2), str(4)
memory usage: 574.0 bytes

In [58]:
clean_data['Salary']=clean_data['Salary'].astype(int)

In [59]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      int64
 3   Location  6 non-null      str
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: int64(3), str(3)
memory usage: 544.0 bytes

In [60]:
clean_data['Name']=clean_data['Name'].astype('category')
clean_data['Domain']=clean_data['Domain'].astype('category')
clean_data['Location']=clean_data['Location'].astype('category')

In [61]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: category(3), int64(3)
memory usage: 529.0 bytes

In [62]:
clean_data.to_csv('clean_data.csv')

In [63]:
import os
os.getcwd()

'C:\\Users\\LENOVO\\Downloads\\PYTHON-CHAPTER-1'