In [1]:
3+5

8

In [2]:
_+2

10

In [3]:
a=2
type(a)

int

In [4]:
a=5
a

5

In [5]:
type(a)

int

In [7]:
id(a)

140705296278776

In [6]:
f=5.5
type(f)

float

In [9]:
print(id(a))
print(id(f))

140705296278776
2320539871088

In [10]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [11]:
len(keyword.kwlist)

35

In [12]:
a=True
a

True

In [13]:
type(a)

bool

In [16]:
a="welcome"
a

'welcome'

In [17]:
a="jehjrefr
dkefjkwfjrw
ejdjhj"

SyntaxError: unterminated string literal (detected at line 1) (799924686.py, line 1)

In [18]:
a='''cjdfjwfjw
jdkjfkfje
wdhdwjfjf'''
a

'cjdfjwfjw\njdkjfkfje\nwdhdwjfjf'

In [19]:
s1="you are great"
s1

'you are great'

In [20]:
s1[0]

'y'

In [21]:
s1[7]

' '

In [22]:
s1[::-1]

'taerg era uoy'

In [23]:
s1[::-4]

'tgay'

In [24]:
s1[0:7]

'you are'

In [25]:
s1[0:11:4]

'yag'

In [26]:
s1[-1:-8:-2]

'tege'

In [27]:
s1[-1:-8]

''

In [28]:
s1[2:]

'u are great'

In [29]:
s1[:7]

'you are'

In [30]:
s1[::]

'you are great'

In [31]:
s1[::1]

'you are great'

In [65]:
s1[:2]

'yo'

In [66]:
s1[2:100]

'u are great'

In [32]:
s1[::2]

'yuaeget'

In [33]:
s1[::3]

'y ert'

In [35]:
a1=2
type(a1)

int

In [36]:
int(10.0)

10

In [37]:
int(True)

1

In [38]:
int(False)

0

In [39]:
int(2+2j)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [40]:
int("10")

10

In [41]:
int("10","20")

TypeError: 'str' object cannot be interpreted as an integer

In [42]:
float(10)

10.0

In [43]:
float(True)

1.0

In [44]:
float(False)

0.0

In [45]:
float(2+2j)

TypeError: float() argument must be a string or a real number, not 'complex'

In [46]:
float("10")

10.0

In [47]:
float("ten")

ValueError: could not convert string to float: 'ten'

In [48]:
bool(10)

True

In [49]:
bool(0)

False

In [50]:
bool(2+2j)

True

In [51]:
bool("10")

True

In [52]:
bool("ten")

True

In [53]:
complex(10)

(10+0j)

In [55]:
complex(10.0,5)

(10+5j)

In [56]:
complex(True)

(1+0j)

In [57]:
complex(False)

0j

In [58]:
complex("20")

(20+0j)

In [59]:
comlex("20","30")

NameError: name 'comlex' is not defined

In [60]:
complex("ten")

ValueError: complex() arg is a malformed string

In [61]:
str(10)

'10'

In [62]:
str(10.0)

'10.0'

In [63]:
str(True)

'True'

In [64]:
str(False)

'False'

In [67]:
5+6
7+8

15

In [68]:
print(5+6)
print(7+8)

11
15

In [70]:
p1=22
p2=30
print(p1)
print(p2)

22
30

In [87]:
p1,p2=30
print(p1)
print(p2)

TypeError: cannot unpack non-iterable int object

In [88]:
p1,p2=80,90
print(p1,p2)

80 90

In [90]:
num1=2
num2=3
add=num1+num2
print(add)

5

In [92]:
num1=2
num2=3
add=num1+num2
print("the adition of num1 and num2 is=",add)

the adition of num1 and num2 is= 5

In [95]:
name='sumayya'
age=20
place="warangal"
print("Her name is",name,"and",age,"year old","she is from",place)

Her name is sumayya and 20 year old she is from warangal

In [99]:
name="sumayya"
age=20
place="warangal"
print("Her name is {} and {} year old she is from {}".format(name,age,place))

Her name is sumayya and 20 year old she is from warangal

In [101]:
name="sumayya"
age=20
place="warangal"
print(f"Her name is {name} and {age} year old she is from {place}")

Her name is sumayya and 20 year old she is from warangal

In [102]:
print("hello",end=" ")
print("sumayya")

hello sumayya

In [274]:
print("helo",sep="**")
print("hor r u")

helo
hor r u

In [272]:
print("hello","how are you",sep="**")

hello**how are you

In [72]:
abc=55
abc

55

In [73]:
12abc=55
12abc

SyntaxError: invalid decimal literal (2623077833.py, line 1)

In [74]:
abc12=55
abc12

55

In [75]:
_abc35=55
_abc35

55

In [76]:
*abc35=55
*abc35

SyntaxError: starred assignment target must be in a list or tuple (1982885908.py, line 1)

In [78]:
abc_=35
abc_

35

In [79]:
abc&=25
abc&

SyntaxError: invalid syntax (2024531907.py, line 2)

In [80]:
Abc=35
Abc

35

In [82]:
bcd=35
Bcd

NameError: name 'Bcd' is not defined

In [84]:
break=8
break

SyntaxError: invalid syntax (107623857.py, line 1)

In [83]:
d1=55
type(q1)

NameError: name 'q1' is not defined

In [85]:
a=True
a

True

In [86]:
true=1
true

1

 # arihtmetic operator(+,-,*,//,/,%,**)

In [104]:
k1=10
k2=10
k1+k2

20

In [105]:
k1-k1

0

In [106]:
k1*k1

100

In [107]:
k1//k2

1

In [108]:
k1/k2

1.0

In [109]:
k1%k2

0

In [110]:
k1**k2

10000000000

assignment opearor(+=,-=,*=,/=,//=,**=)

In [114]:
ass1=10
ass1+=2
ass1

12

In [115]:
ass1-=2
ass1

10

In [116]:
ass1*=5
ass1

50

relational opearot or compariion opearor:(><>=<=,==,!=)

In [117]:
a=5
b=6
print(a>b)

False

In [118]:
print(a!=b)

True

logical operator: or and not

In [119]:
d=8
e=7
print(a>b and d<e)

False

In [120]:
a=True
print(a)

True

In [125]:
not a

False

In [126]:
x=False
not x

True

In [127]:
bin(28)

'0b11100'

In [139]:
bin(1)

'0b1'

In [128]:
0b11100

28

In [134]:
int(0b11100)

28

In [129]:
oct(28)

'0o34'

In [140]:
oct(1)

'0o1'

In [141]:
oct(8)

'0o10'

In [130]:
0o34

28

In [133]:
int(0o34)

28

In [131]:
hex(10)

'0xa'

In [132]:
hex(1)

'0x1'

In [135]:
hex(2)

'0x2'

In [136]:
hex(3)

'0x3'

In [142]:
hex(15)

'0xf'

In [143]:
hex(16)

'0x10'

In [144]:
int(0x10)

16

In [145]:
hex(19)

'0x13'

In [146]:
int(0x13)

19

In [148]:
0x13

19

In [149]:
a1,b1=7,8
a1,b1=b1,a1
print(a1)
print(b1)

8
7

In [151]:
a=8
b=6
temp=a
a=b
b=temp
print(a)
print(b)

6
8

# Binary number system 0b(1 and 0)
# octal number system 0o(0,1,2,3,4,5,6,7)
# Decimal number system (o,1,2,3,4,5,6,7,8,9)
# Hexadecimal number system(0,1,2,3,4,,5,6,7,8,9,a,b,c,d,e,f)(0t015) 0hex

In [152]:
bin(36)

'0b100100'

In [153]:
0b100100

36

In [154]:
int(0b100100)

36

In [155]:
bin(42)

'0b101010'

In [156]:
0b101010

42

In [157]:
int(0b101010)

42

In [159]:
oct(46)

'0o56'

In [160]:
0o56

46

In [162]:
oct(8)

'0o10'

In [161]:
int(0o56)

46

In [163]:
hex(10)

'0xa'

In [164]:
hex(20)

'0x14'

In [165]:
~14

-15

In [168]:
14 & 16

0

In [169]:
bin(16)

'0b10000'

In [170]:
12 & 13

12

In [171]:
14 & 16

0

In [172]:
18|20

22

In [173]:
42 ^ 88

114

In [174]:
12<<14

196608

In [175]:
12<<2

48

In [176]:
12>>2

3

In [177]:
5+5

10

In [178]:
5-5

0

In [196]:
print("Hi, \n How are you\n fine\n\'Thank you'")

Hi,
 How are you
 fine
'Thank you'

In [197]:
0b110101

53

In [198]:
oct(8)

'0o10'

In [199]:
oct(24)

'0o30'

In [200]:
int(0o30)

24

In [201]:
hex(16)

'0x10'

In [202]:
hex(82)

'0x52'

In [204]:
int(0x52)

82

bitwise operator

In [205]:
n=2
m=-(n)
m

-2

In [210]:
print("2","3",sep="@@")

2@@3

In [214]:
print("2","45",end="\n")
print("3")

2 45
3

In [217]:
l1=23
l2=45
l3=66
l4=23
print(l1>l2 or l3<l4)

False

In [218]:
23 | 45

63

In [219]:
23 ^ 45

58

In [220]:
12<<3

96

In [221]:
12<3

False

In [222]:
12>>3

1

In [223]:
a=2
b=3
a=b
b=a
print(a)
print(b)

3
3

In [224]:
a,b=5,6
a,b=b,a
print(a,b)

6 5

In [225]:
a=2
b=3
print(a)
print(b)

2
3

In [226]:
print(a,b)

2 3

In [227]:
print(1,"smayya",2)

1 smayya 2

In [237]:
a=5
b=7
add=a+b
print("The addition of a and b is=",add)
print("The addition of {} and {} is={}".format(a,b,add))
print(f"The addition of {a} and {b} is=",add)
print("The addition of a",end=" ")
print("and the addition of b is",add)
print(add)

The addition of a and b is= 12
The addition of 5 and 7 is=12
The addition of 5 and 7 is= 12
The addition of a and the addition of b is 12
12

In [238]:
print("Hello","world")

Hello world

In [239]:
x="Hello"
print(len(x))

5

In [241]:
x=" Hello world "
print(x.strip())
x[1:12]

Hello world

'Hello world'

##### a="join"
b="the"
c="party"
print(a,'',b,'',c,'')

In [246]:
x=25
x

25

In [247]:
x=sqrt(25)
x

NameError: name 'sqrt' is not defined

In [248]:
x=math.sqrt(25)
x

NameError: name 'math' is not defined

In [249]:
import math
x=math.sqrt(25)
x

5.0

In [250]:
x=math.floor(9.8)
x

9

In [251]:
x=math.ceil(8.7)
x

9

In [252]:
x=math.pow(4,2)
x

16.0

In [257]:
import math as m
print(m.sqrt(25))
print(m.floor(3.4))
print(m.ceil(7))
print(m.pow(2,3))

5.0
3
7
8.0

In [271]:
from math import as m
print(m.sqrt(25))
print(m.floor(3.4))
print(m.ceil(7))
print(m.pow(2,3))

SyntaxError: invalid syntax (1134659645.py, line 1)

In [260]:
from math import sqrt,floor,ceil,pow
print(sqrt(25))
print(floor(3.4))
print(ceil(7))
print(pow(2,3))

5.0
3
7
8.0

In [261]:
from math import *
print(sqrt(25))
print(floor(3.4))
print(ceil(7))
print(pow(2,3))

5.0
3
7
8.0

In [262]:
x=input()
x

 5

'5'

In [263]:
x=int(input("Enter the value 1:"))
y=int(input("Enter the value 2:"))
z=x+y
print(z)

Enter the value 1: 5
Enter the value 2: 5

10

In [264]:
x=(input("Enter the value 1:"))
y=(input("Enter the value 2:"))
z=x+y
print(z)

Enter the value 1: 5
Enter the value 2: 5

55

In [265]:
x=input("Enter your name:")
x

Enter your name: Sumayya

'Sumayya'

In [266]:
x=input("ENTER YOUR NAME:")
y=input('ENTER YOUR PASSWORD:')
print(x,y)

ENTER YOUR NAME: Sumayya koaunain
ENTER YOUR PASSWORD: 736374673463

Sumayya koaunain 736374673463

In [269]:
x=int(input("Enter your aadhar no.:")[8:])
print(x)

Enter your aadhar no.: 1234567876543

76543

In [270]:
x=int(input("Enter your aadhar no.:"))[8:]
print(x)

Enter your aadhar no.: 543253346343

TypeError: 'int' object is not subscriptable

In [275]:
x=input("enter the expression")
x

enter the expression 2-23-2-34

'2-23-2-34'

In [276]:
x=eval(input("enter the expression"))
x

enter the expression 2-2-2-4+6

0

In [277]:
print(f"The result of {2+3} is:")

The result of 5 is:

In [278]:
if [1,2] is [1,2]

SyntaxError: expected ':' (2013948095.py, line 1)

In [286]:
a=(input("Enter the adhar number"))
print(a[8:])

Enter the adhar number 123456785432

5432

In [283]:
a="apple"
a[0]

'a'

In [289]:
a=(input("Enter the expression"))
a

Enter the expression 1-3-4-56-6

'1-3-4-56-6'

In [292]:
a=eval(input("Enter the expression"))
print(a)

Enter the expression 2-2-3-2

-5

In [293]:
l1=[10,3.5,True,(1+2j),'welcome']
l1[::3]

[10, (1+2j)]

In [294]:
l=[]
l

[]

In [297]:
type(l)

list

In [298]:
len(l)

0

In [299]:
l=[1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [300]:
len(l)

5

In [301]:
type(l)

list

In [302]:
l.append(10)
l

[1, 2, 3, 4, 5, 10]

In [304]:
l.append(20)
l.append(30)
l.append(40)
l

[1, 2, 3, 4, 5, 10, 20, 30, 40]

In [307]:
m2

NameError: name 'm2' is not defined

In [310]:
l1=[1,2,34,5,7]
l2=[4,56,6,8,45,9]
l3=[5,55,3,9,7,4]

In [311]:
l3.clear()

In [312]:
print(l1)
print(l2)
print(l3)

[1, 2, 34, 5, 7]
[4, 56, 6, 8, 45, 9]
[]

In [313]:
del(l3)

In [314]:
print(l1)
print(l2)
print(l3)

[1, 2, 34, 5, 7]
[4, 56, 6, 8, 45, 9]

NameError: name 'l3' is not defined

In [317]:
l3=l1.copy()

In [318]:
print(l1)
print(l2)
print(l3)

[1, 2, 34, 5, 7]
[4, 56, 6, 8, 45, 9]
[1, 2, 34, 5, 7]

In [322]:
l1.count(5)

1

In [324]:
l1.extend(l2)
l1

[1, 2, 34, 5, 7, 1, 2, 34, 5, 7, 4, 56, 6, 8, 45, 9]

In [325]:
l1=[1,2,3,45,7,8]
l1

[1, 2, 3, 45, 7, 8]

In [326]:
l1[0]

1

In [336]:
l1.index(3)

2

In [327]:
l1[2]

3

In [329]:
l1[2:3]

[3]

In [330]:
l1[::-1]

[8, 7, 45, 3, 2, 1]

In [331]:
l1[::-2]

[8, 45, 2]

In [328]:
l6=[1,2,4,5,"welcome",(1+2j),[1,2,3]]
l6

[1, 2, 4, 5, 'welcome', (1+2j), [1, 2, 3]]

In [332]:
l6[4]

'welcome'

In [337]:
l6[4][1]

'e'

In [338]:
a=3
b=4
a,b=b,a
print(a)
print(b)

4
3

In [341]:
print("hi")
print("how are you")

hi
how are you

In [340]:
print("yes","how are you",sep="***")

yes***how are you

In [342]:
a=10
b=15
add=a+b
print(f"The addition of {a} and {b} is={add}")

The addition of 10 and 15 is=25

In [343]:
l=[]
l

[]

In [344]:
len(l)

0

In [345]:
l=[1,2,34]
l

[1, 2, 34]

In [346]:
len(l)

3

In [347]:
l.append(20)
l.append(30)
l

[1, 2, 34, 20, 30]

In [348]:
l.append(1)
l

[1, 2, 34, 20, 30, 1]

In [349]:
l2

[4, 56, 6, 8, 45, 9]

In [350]:
[1,2] is [1,2]

False

In [352]:
t1=()
t1

()

In [353]:
type(t1)

tuple

In [354]:
t1=(1,2,34,5)
t1

(1, 2, 34, 5)

In [355]:
t1=(1,2,34,5,5)
t1

(1, 2, 34, 5, 5)

In [357]:
t1.index(2)

1

In [358]:
l=[]
l

[]

In [359]:
len(l)

0

In [360]:
id(l)

2320553982784

In [361]:
type(l)

list

In [362]:
l.append(10)
l.append(20)
l.append(30)
l.append(40)
l

[10, 20, 30, 40]

In [363]:
len(l)

4

In [364]:
type(l)

list

In [365]:
l.append(10)
l

[10, 20, 30, 40, 10]

In [366]:
l1=[1,2,3,(2+2j),'welcome']
l1

[1, 2, 3, (2+2j), 'welcome']

In [367]:
type(l1)

list

In [369]:
l7

NameError: name 'l7' is not defined

In [370]:
l7=l1.copy()
l7

[1, 2, 3, (2+2j), 'welcome']

In [371]:
len(l7)==len(l1)

True

In [372]:
id(l7)==id(l1)

False

In [373]:
id(l7)

2320548922944

In [374]:
id(l1)

2320555684352

In [375]:
id(l7)!=id(l1)

True

In [376]:
l7.clear()

In [377]:
print(l1)
print(l7)

[1, 2, 3, (2+2j), 'welcome']
[]

In [378]:
del(l7)

In [379]:
print(l1)
print(l7)

[1, 2, 3, (2+2j), 'welcome']

NameError: name 'l7' is not defined

In [380]:
l1=[1,2,34,5,6]
l7=[1,2,3,(2+2j),'welcome']

In [381]:
l7.extend(l1)

In [382]:
l7

[1, 2, 3, (2+2j), 'welcome', 1, 2, 34, 5, 6]

In [383]:
print(len(l1))
print(len(l7))

5
10

In [384]:
l7.insert(4,'shutup')

In [385]:
l7

[1, 2, 3, (2+2j), 'shutup', 'welcome', 1, 2, 34, 5, 6]

In [386]:
l7.pop()

6

In [388]:
l7

[1, 2, 3, (2+2j), 'shutup', 'welcome', 1, 34, 5]

In [389]:
l7.pop(-3)

1

In [390]:
l7.pop(2)

3

In [392]:
l7

[1, 2, (2+2j), 'shutup', 'welcome', 34, 5]

In [393]:
l7.index(2+2j)

2

In [394]:
l7[0]

1

In [395]:
l7.index('welcome')

4

In [396]:
l7

[1, 2, (2+2j), 'shutup', 'welcome', 34, 5]

In [397]:
print(l7[4][0])
print(l7[4][1])
print(l7[4][2])

w
e
l

In [398]:
l7[2:]

[(2+2j), 'shutup', 'welcome', 34, 5]

In [399]:
l7[::-1]

[5, 34, 'welcome', 'shutup', (2+2j), 2, 1]

In [400]:
l7[::2]

[1, (2+2j), 'welcome', 5]

In [401]:
l7[::-3]

[5, 'shutup', 1]

In [402]:
l7[::-4]

[5, (2+2j)]

In [403]:
l7.reverse()

In [404]:
l7

[5, 34, 'welcome', 'shutup', (2+2j), 2, 1]

In [405]:
l7.remove('shutup')

In [406]:
l7

[5, 34, 'welcome', (2+2j), 2, 1]

In [407]:
l8=[1,2,34,2,5,6]
l8

[1, 2, 34, 2, 5, 6]

In [408]:
l8.count(2)

2

In [409]:
l8.sort()
l8

[1, 2, 2, 5, 6, 34]

In [410]:
l8.sort(reverse=True)
l8

[34, 6, 5, 2, 2, 1]

In [411]:
l7.sort()
l7

TypeError: '<' not supported between instances of 'str' and 'int'

In [412]:
l8[0]=100
l8

[100, 6, 5, 2, 2, 1]

In [413]:
2 in l8

True

In [414]:
all(l8)

True

In [415]:
any(l8)

True

In [416]:
l8=[0,1,23,4]
l8

[0, 1, 23, 4]

In [417]:
all(l8)

False

In [418]:
t=()
t

()

In [419]:
type(t)

tuple

In [420]:
len(t)

0

In [421]:
id(t)

140705296355032

In [422]:
t=(1,2,3,5.6,'hello',True)

In [423]:
t

(1, 2, 3, 5.6, 'hello', True)

In [424]:
len(t)

6

In [425]:
type(t)

tuple

In [426]:
id(t)

2320542173312

In [427]:
t=(1,2,3,4,'hello',True,True)
t

(1, 2, 3, 4, 'hello', True, True)

In [428]:
t.remove(True)
t

AttributeError: 'tuple' object has no attribute 'remove'

In [429]:
t.reverse()
t

AttributeError: 'tuple' object has no attribute 'reverse'

In [430]:
t.pop()

AttributeError: 'tuple' object has no attribute 'pop'

In [439]:
t7=(1,2,3,5,True,True)

In [441]:
t7.count(5)

1

In [442]:
t0=(1,2,3,4,5)
t8=(5,6,7,8,9)

In [443]:
t0

(1, 2, 3, 4, 5)

In [444]:
t8

(5, 6, 7, 8, 9)

In [445]:
t8=t0.copy()
t8

AttributeError: 'tuple' object has no attribute 'copy'

In [446]:
t8

(5, 6, 7, 8, 9)

In [447]:
t8.index(9)

4

In [448]:
t8

(5, 6, 7, 8, 9)

In [449]:
t8=(1,2,34,5,(2+2j),(7,8,9))

In [450]:
t8

(1, 2, 34, 5, (2+2j), (7, 8, 9))

In [451]:
print(t8[5][0])

7

In [452]:
print(t8[5][1])
print(t8[5][2])

8
9

In [454]:
t8[5][1]=10

TypeError: 'tuple' object does not support item assignment

In [455]:
t8

(1, 2, 34, 5, (2+2j), (7, 8, 9))

In [456]:
t8*3

(1,
 2,
 34,
 5,
 (2+2j),
 (7, 8, 9),
 1,
 2,
 34,
 5,
 (2+2j),
 (7, 8, 9),
 1,
 2,
 34,
 5,
 (2+2j),
 (7, 8, 9))

In [457]:
l1

[1, 2, 34, 5, 6]

In [458]:
l1*2

[1, 2, 34, 5, 6, 1, 2, 34, 5, 6]

In [459]:
s={}
s

{}

In [460]:
len(s)

0

In [461]:
type(s)

dict

In [462]:
s={1,23,4}
s

{1, 4, 23}

In [463]:
type(s)

set

In [464]:
s=set()
type(s)

set

In [465]:
s={1,2,3,4,4.6,"hyderabad"}
s

{1, 2, 3, 4, 4.6, 'hyderabad'}

In [466]:
s1={2,1,46,3,"hyderbad"}
s1

{1, 2, 3, 46, 'hyderbad'}

In [467]:
s1={'apple','mango','banana'}
s1

{'apple', 'banana', 'mango'}

In [468]:
s1.add('cherry')

In [469]:
s1

{'apple', 'banana', 'cherry', 'mango'}

In [470]:
s2={1,2,34,5,6}
s2.add(0)
s2

{0, 1, 2, 5, 6, 34}

In [471]:
s3

NameError: name 's3' is not defined

In [472]:
s3=s2.copy()
s3

{0, 1, 2, 5, 6, 34}

In [473]:
s3

{0, 1, 2, 5, 6, 34}

In [474]:
s3.clear()

In [475]:
print(s1)
print(s2)
print(s3)

{'mango', 'banana', 'cherry', 'apple'}
{0, 1, 2, 34, 5, 6}
set()

In [476]:
del(s3)

In [477]:
print(s1)
print(s2)
print(s3)

{'mango', 'banana', 'cherry', 'apple'}
{0, 1, 2, 34, 5, 6}

NameError: name 's3' is not defined

In [478]:
s2.count(5)

AttributeError: 'set' object has no attribute 'count'

In [479]:
s2.remove(5)

In [480]:
s2

{0, 1, 2, 6, 34}

In [481]:
s2.remove(100)

KeyError: 100

In [482]:
s2.discard(6)

In [483]:
s2

{0, 1, 2, 34}

In [484]:
s2.discard(100)

In [485]:
s2

{0, 1, 2, 34}

In [486]:
s2.index(1)

AttributeError: 'set' object has no attribute 'index'

In [487]:
s2[0]

TypeError: 'set' object is not subscriptable

In [488]:
s2[0]=100

TypeError: 'set' object does not support item assignment

In [489]:
s2[0:2]

TypeError: 'set' object is not subscriptable

In [490]:
s2

{0, 1, 2, 34}

In [491]:
s2.pop()

0

In [492]:
s2.pop(2)

TypeError: set.pop() takes no arguments (1 given)

In [493]:
a={1,2,3,4,5,6}
b={4,5,6,7,8,9}
c={10,11,12,13}

In [494]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [495]:
b.union(a)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [496]:
b.union(c)

{4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

In [497]:
a.union(c)

{1, 2, 3, 4, 5, 6, 10, 11, 12, 13}

In [502]:
a|b|c

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

In [498]:
a.intersection(b)

{4, 5, 6}

In [499]:
b.intersection(a)

{4, 5, 6}

In [500]:
b.intersection(c)

set()

In [501]:
a.intersection(c)

set()

In [503]:
a & b & c

set()

In [505]:
a.difference(b)

{1, 2, 3}

In [506]:
b.difference(a)

{7, 8, 9}

In [507]:
c.difference(b)

{10, 11, 12, 13}

In [508]:
c - b

{10, 11, 12, 13}

In [509]:
c.symmetric_difference(b)

{4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

In [510]:
c.union(b)

{4, 5, 6, 7, 8, 9, 10, 11, 12, 13}

In [511]:
a.symmetric_difference(b)

{1, 2, 3, 7, 8, 9}

In [513]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [514]:
a.symmetric_difference_update(b)

In [515]:
a

{1, 2, 3, 7, 8, 9}

In [545]:
a1={4,5,6,7,8,9,10}
a2={4,5,6,7,11}
a3={11,12,13}

In [546]:
a1.issuperset(a2)

False

In [547]:
a2.issubset(a1)

False

In [548]:
a1.isdisjoint(a3)

True

In [549]:
a1

{4, 5, 6, 7, 8, 9, 10}

In [550]:
a4=frozenset(a1)
a4

frozenset({4, 5, 6, 7, 8, 9, 10})

In [551]:
a4.add(11)
a4

AttributeError: 'frozenset' object has no attribute 'add'

In [552]:
type(a4)

frozenset

In [553]:
b3={30,40,50,60,70,80}
c3={10,20,30,40}

In [554]:
b3.issubset(c3)

False

In [555]:
c3.issubset(b3)

False

In [556]:
c3.isdisjoint(b3)

False

In [570]:
a2.issuperset(b2)

True

In [571]:
b2.issuperset(a2)

False

In [572]:
a2.issubset(b2)

False

In [569]:
a2={1,2,3,4,5,6,7,8,9,10,11}
b2={3,4,5,6,7,8}
c2={10,20,30,40}

In [573]:
b2.issubset(a2)

True

In [574]:
a2.isdisjoint(b2)

False

In [576]:
b2.isdisjoint(a2)

False

In [577]:
c2.isdisjoint(b2)

True

In [578]:
c2.issubset(a2)

False

In [579]:
a2.issuperset(c2)

False

In [580]:
c2.issuperset(a2)

False

In [583]:
b4=frozenset(c2)
b4

frozenset({10, 20, 30, 40})

In [584]:
type(b4)

frozenset

In [585]:
range(5)

range(0, 5)

In [586]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [587]:
list(range(20,30))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [588]:
list(range(20,30,2))

[20, 22, 24, 26, 28]

In [589]:
list(range(20,20,2,2))

TypeError: range expected at most 3 arguments, got 4

In [591]:
x=2
r=x%2
if r==0:
    print('Even number')

Even number

In [592]:
x=2
r=x%2
if r==0:
    print('Even number')
print('odd number')

Even number
odd number

In [593]:
x=2
r=x%2
if r==0:
    print('Even number')
else:
    print('odd number')

Even number

In [594]:
x=3
r=x%2
if r==0:
    print('Even number')

In [595]:
x=3
r=x%2
if r==0:
    print('Even number')
else:
    print('odd number')

odd number

In [600]:
x=4
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('yes')
    else:
        print('no')
else:
    print('odd number')

Even number
no

In [609]:
x=12
r=x%2
if r==0:
    print('Even number')
    if x>2:
        print("yes")
    else:
        print("n0")
else:
    print('Odd number')

Even number
yes

In [613]:
x=9
if x>18:
    print("Yes he is eligible for vote")
else:
    print("He is not eligible for vote")

He is not eligible for vote

In [618]:
x=5
if x==1:
    print("one")
elif x<2:
    print("two")
elif x==3:
    print('three')
elif x==4:
    print('four')
else:
    print("enter")

enter

In [1]:
d=dict()
d

{}

In [2]:
type(d)

dict

In [3]:
d1=dict({1:"apple",2:"banana",3:"cherry"})
d1

{1: 'apple', 2: 'banana', 3: 'cherry'}

In [4]:
d1=dict({1:"apple",2:"banana",3:"cherry",4:[1,2,3,4]})
d1

{1: 'apple', 2: 'banana', 3: 'cherry', 4: [1, 2, 3, 4]}

In [5]:
s={1:"apple",2:"banana",3:"cherry",4:[5,6,7,9]}
s

{1: 'apple', 2: 'banana', 3: 'cherry', 4: [5, 6, 7, 9]}

In [6]:
s={1:"apple",2:"banana",3:"cherry",[5,6,7,9]:"rwa"}
s

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [14]:
s={1:"apple",2:"banana",3:"cherry",4:[5,6,7,9],[1,2,3]:5}
s

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [16]:
s1=dict()
s1

{}

In [17]:
type(s1)

dict

In [23]:
s1={1,2,3}
s2=dict.fromkeys(s1)
s2

{1: None, 2: None, 3: None}

In [27]:
s1={1,2,3}
s3=1
s2=dict.fromkeys(s1,s3)
s2

{1: 1, 2: 1, 3: 1}

In [28]:
s1={1,2,3}
s3=[1,2,3]
s2=dict.fromkeys(s1,s3)
s2

{1: [1, 2, 3], 2: [1, 2, 3], 3: [1, 2, 3]}

In [29]:
s1={1,2,3,[2,3]}
s3=[1,2,3]
s2=dict.fromkeys(s1,s3)
s2

TypeError: cannot use 'list' as a set element (unhashable type: 'list')

In [30]:
s1={1,2,3,(2,3)}
s3=[1,2,3]
s2=dict.fromkeys(s1,s3)
s2

{(2, 3): [1, 2, 3], 1: [1, 2, 3], 2: [1, 2, 3], 3: [1, 2, 3]}

In [31]:
s2

{(2, 3): [1, 2, 3], 1: [1, 2, 3], 2: [1, 2, 3], 3: [1, 2, 3]}

In [34]:
s1.append(40)
s2

AttributeError: 'set' object has no attribute 'append'

In [35]:
s2

{(2, 3): [1, 2, 3, 40], 1: [1, 2, 3, 40], 2: [1, 2, 3, 40], 3: [1, 2, 3, 40]}

In [36]:
s2[1]

[1, 2, 3, 40]

In [40]:
s2[(2,3)]

[1, 2, 3, 40]

In [38]:
s2[2]

[1, 2, 3, 40]

In [39]:
s2.get(1)

[1, 2, 3, 40]

In [41]:
s2.get(1)

[1, 2, 3, 40]

In [42]:
s2

{(2, 3): [1, 2, 3, 40], 1: [1, 2, 3, 40], 2: [1, 2, 3, 40], 3: [1, 2, 3, 40]}

In [44]:
s2.remove(40)

AttributeError: 'dict' object has no attribute 'remove'

In [72]:
s={1:"apple",2:"orange",3:"cherry"}

In [73]:
s

{1: 'apple', 2: 'orange', 3: 'cherry'}

In [74]:
s[0]="raw"

In [75]:
s

{1: 'apple', 2: 'orange', 3: 'cherry', 0: 'raw'}

In [76]:
s

{1: 'apple', 2: 'orange', 3: 'cherry', 0: 'raw'}

In [77]:
s2={5:"furr"}
s.update(s2)
s

{1: 'apple', 2: 'orange', 3: 'cherry', 0: 'raw', 5: 'furr'}

In [78]:
s

{1: 'apple', 2: 'orange', 3: 'cherry', 0: 'raw', 5: 'furr'}

In [79]:
s.pop(0)

'raw'

In [80]:
s

{1: 'apple', 2: 'orange', 3: 'cherry', 5: 'furr'}

In [81]:
s.popitem()

(5, 'furr')

In [82]:
s

{1: 'apple', 2: 'orange', 3: 'cherry'}

In [83]:
s.clear()

In [84]:
s

{}

In [85]:
del[s['apple']]

KeyError: 'apple'

In [86]:
s

{}

In [89]:
s1={1:"keys",2:"values",3:"orange"}
s2={4:"abs","hello":"abc","abs":22}

In [90]:
len(s1)

3

In [91]:
len(s2)

3

In [92]:
s1.clear()

In [93]:
print(s1)
print(s2)

{}
{4: 'abs', 'hello': 'abc', 'abs': 22}

In [94]:
del(s1)

In [95]:
print(s2)
print(s1)

{4: 'abs', 'hello': 'abc', 'abs': 22}

NameError: name 's1' is not defined

In [98]:
del s1

NameError: name 's1' is not defined

In [99]:
s3

[1, 2, 3, 40]

In [100]:
s6

NameError: name 's6' is not defined

In [103]:
s6=s3.copy()

In [104]:
s6

[1, 2, 3, 40]

In [105]:
s6

[1, 2, 3, 40]

In [106]:
s1={1:"keys",2:"values",3:"orange"}
s1

{1: 'keys', 2: 'values', 3: 'orange'}

In [107]:
1 in s1

True

In [108]:
"keys" in s1

False

In [109]:
s1

{1: 'keys', 2: 'values', 3: 'orange'}

In [110]:
all(s1)

True

In [119]:
s1={1:"keys",2:"values",3:"orange",4:(2+2j),"yes":0}
s1

{1: 'keys', 2: 'values', 3: 'orange', 4: (2+2j), 'yes': 0}

In [120]:
all(s1)

True

In [ ]:
s1[

In [121]:
d={}
d

{}

In [122]:
type(d)

dict

In [123]:
d1=dict()
d1

{}

In [124]:
type(d1)

dict

In [125]:
d2={1:"welcome",2:"true","abc":(2+2j)}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j)}

In [126]:
d2={1:"welcome",2:"true","abc":(2+2j),4:[1,2,3]}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), 4: [1, 2, 3]}

In [127]:
d2={1:"welcome",2:"true","abc":(2+2j),[1,2,3]:4}
d2

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [128]:
d2={1:"welcome",2:"true","abc":(2+2j),4:(1,2,3)}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), 4: (1, 2, 3)}

In [129]:
d2={1:"welcome",2:"true","abc":(2+2j),(1,2,3):4}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), (1, 2, 3): 4}

In [130]:
d2={1:"welcome",2:"true","abc":(2+2j),4:(1,2,3),5:{4:"yes"}}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), 4: (1, 2, 3), 5: {4: 'yes'}}

In [131]:
d2={1:"welcome",2:"true","abc":(2+2j),4:(1,2,3),5:{1,2,3}}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), 4: (1, 2, 3), 5: {1, 2, 3}}

In [132]:
d2={1:"welcome",2:"true","abc":(2+2j),4:(1,2,3),2:"false"}
d2

{1: 'welcome', 2: 'false', 'abc': (2+2j), 4: (1, 2, 3)}

In [133]:
d2={1:"welcome",2:"true","abc":(2+2j),4:(1,2,3),5:(1,2,3)}
d2

{1: 'welcome', 2: 'true', 'abc': (2+2j), 4: (1, 2, 3), 5: (1, 2, 3)}

In [135]:
d2[0]="beauty"

In [136]:
d2

{1: 'welcome',
 2: 'true',
 'abc': (2+2j),
 4: (1, 2, 3),
 5: (1, 2, 3),
 0: 'beauty'}

In [212]:
d3={100:"raw"}
d2.update(d3)
d2

{1: 'welcome',
 2: 'true',
 'abc': (2+2j),
 4: (1, 2, 3),
 5: (1, 2, 3),
 0: 'beauty',
 100: 'raw'}

In [217]:
d2[100]="rrr"

In [218]:
d2

{1: 'welcome',
 2: 'true',
 'abc': (2+2j),
 4: (1, 2, 3),
 5: (1, 2, 3),
 0: 'beauty',
 100: 'rrr'}

In [139]:
d2[1]

'welcome'

In [143]:
d2[0]

'beauty'

In [145]:
d2

{1: 'welcome',
 2: 'true',
 'abc': (2+2j),
 4: (1, 2, 3),
 5: (1, 2, 3),
 0: 'beauty',
 100: 'raw'}

In [146]:
d2.get("welcome")

In [147]:
d2

{1: 'welcome',
 2: 'true',
 'abc': (2+2j),
 4: (1, 2, 3),
 5: (1, 2, 3),
 0: 'beauty',
 100: 'raw'}

In [148]:
d2.get(100)

'raw'

In [152]:
r={1,2,3}
b=dict.fromkeys(r)
b

{1: None, 2: None, 3: None}

In [153]:
r={1,2,3}
v={"yes"}
b=dict.fromkeys(r,v)
b

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [154]:
b

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [156]:
b1=b

In [157]:
b1

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [158]:
print(id(b))
print(id(b1))

3141565164224
3141565164224

In [159]:
h=b.copy()
h

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [160]:
print(id(b))
print(id(h))

3141565164224
3141564452032

In [167]:
h

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [170]:
h1={4:"wow"}
h.update(h1)
h

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}, 4: 'wow'}

In [171]:
h

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}, 4: 'wow'}

In [172]:
b

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [173]:
b1

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}}

In [174]:
b2={4:"wow"}
b1.update(b2)
b1

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}, 4: 'wow'}

In [175]:
b

{1: {'yes'}, 2: {'yes'}, 3: {'yes'}, 4: 'wow'}

In [176]:
b.clear()

In [177]:
b

{}

In [178]:
b.pop()

TypeError: pop expected at least 1 argument, got 0

In [205]:
c={1:"apple",2:"banana",3:"kiwiw"}
c

{1: 'apple', 2: 'banana', 3: 'kiwiw'}

In [206]:
c.popitem()

(3, 'kiwiw')

In [219]:
c

{1: 'apple', 2: 'banana'}

In [220]:
del(c[1])

In [221]:
c

{2: 'banana'}

In [222]:
x=int(input("Enter the age"))
if x>18:
    print("you can vote")
else:
    print("no")

Enter the age 19

you can vote

In [223]:
x=int(input("Enter the age"))
if x>18:
    print("you can vote")
    print("no")

Enter the age 7

In [224]:
x=int(input("Enter the age"))
if x>18:
    print("you can vote")
    print("no")

Enter the age 19

you can vote
no

In [230]:
x=2
r=x%2
if r==0:
      print("yes")

yes

In [229]:
x=3
if x==2:
    print('one')
elif x==3:
    print('two')

two

In [231]:
print("data")
print("data")
print("data")
print("data")
print("data")

data
data
data
data
data

In [233]:
i=1 
while i<=5:
    print("data",i)
    i=i+1

data 1
data 2
data 3
data 4
data 5

In [4]:
i=5
while(i>=1):
    print("data",i)
    i=i-1

data 5
data 4
data 3
data 2
data 1

In [12]:
i=1
while(i<=5):
    print("data")
    j=1
    while(j<=4):
          print("technology")
          j=j+1
    i=i+1
    print()

data
technology
technology
technology
technology

data
technology
technology
technology
technology

data
technology
technology
technology
technology

data
technology
technology
technology
technology

data
technology
technology
technology
technology

In [3]:
i=5
while i>=1:
    print("yes",i)
    i=i-1

yes 5
yes 4
yes 3
yes 2
yes 1

In [4]:
i=1
while i<=5:
    print("data",end='-')
    j=1
    while j<=4:
        print("science",end='-')
        j=j+1
    i=i+1
    print()

data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-

In [5]:
i=input("enter the value")
i

enter the value 5

'5'

In [8]:
i=int(input("enter the integer"))
print(i)

enter the integer 5

5

In [9]:
f=float(input("enter the integer"))
print(f)

enter the integer 5

5.0

In [3]:
values=input("enter space-separated value:").split(",")
print(values)

enter space-separated value: 5,6,7

['5', '6', '7']

In [6]:
num=int(input("Enter the number"))
if num>0:
    print("yes number is positive")
elif num<0:
    print("number is negative")
else:
    print("zero")

Enter the number -1

number is negative

In [14]:
num=[int(x) for x in input("Enter the number:").split()]
print(num)

Enter the number: 1 2 3

[1, 2, 3]

In [16]:
s=input("enter the string")
print(s.upper())

enter the string sumayya

SUMAYYA

In [17]:
num=input("enter the numbers").split()
print(num)

enter the numbers a b c

['a', 'b', 'c']

In [18]:
num=[int(x) for x in input("enter").split()]
print(num)

enter 1 2 3 4 5 6

[1, 2, 3, 4, 5, 6]

In [26]:
english=input("enter the string")
vowels="aeiou"
count=sum(1 for char in english if char.lower() in vowels)
print("Number of vowels:",count)

enter the string education

Number of vowels: 5

In [29]:
i=int(input("enter the number"))
if i%2==0:
    print("yes")
else:
    print("no")

enter the number 5

no

In [34]:
i=input("enter the number")
if i==i[::-1]:
    print("yes")
else:
    print("no")

enter the number theeht

yes

In [3]:
s=int(input("enter the number:"))
print("Square:",s*2)

enter the number: 5

Square: 10

In [7]:
i=int(input("enter hte number:"))
if i%3==0 and i%7==0:
    print("yes")
else:
    print("no")

enter hte number: 15

no

In [9]:
i=[x for x in input("enter the values").split()]
print(i)

enter the values apple banana cherry

['apple', 'banana', 'cherry']

In [18]:
s=int(input("enter the number:"))
b=int(input("enter the value"))
c=s*b
print("the product of two numbers",)

enter the number: 5
enter the value 2

the product of two numbers 10

In [ ]:
p=int(input("enter the number"))
if p>1:

In [20]:
i=int(input("enter the number:"))
print(i,type(i))

enter the number: 5

5 <class 'int'>

In [21]:
f=float(input("enter the number:"))
print(f,type(f))

enter the number: 5

5.0 <class 'float'>

In [1]:
values=input("enter the space-separated values:").split()
print(values)

enter the space-separated values: 5 6 7

['5', '6', '7']

In [8]:
num=int(input("enter the number"))
if num>0:
    print("num is positive")
elif num<0:
    print("number is negative")
else:
    print("num is zero")

enter the number -1

number is negative

In [12]:
i=[int(x)for x in input("Enter the value").split()]
print(i)

Enter the value 1 2 3 4 5

[1, 2, 3, 4, 5]

In [13]:
s=input("enter the string").upper()
print(s)

enter the string sumayya

SUMAYYA

In [15]:
english=input("enter the words")
vowels="aeiou"
print()

enter the words sumayya

AttributeError: 'str' object has no attribute 'vowels'

In [17]:
i=int(input("enter the number"))
if i%2==0:
    print("number is even")
else:
    print("number is odd")

enter the number 5

number is odd

In [19]:
s=input("enter the palindrome")
if s==s[::-1]:
    print("yes this is laindrom")
else:
    print("no")

enter the palindrome cheaaehc

yes this is laindrom

In [21]:
i=int(input("enter the number"))
s=i**2
print(s)

enter the number 5

25

In [23]:
i=int(input("enter the number"))
if i%3==0:
    print("yes")
else:
    print("no")

enter the number 7

no

In [26]:
i=int(input("enter the number"))
if i%3==0 and i%7==0:
    print("yes")
else:
    print("no")

enter the number 15

no

In [1]:
i=[int(x) for x in input("enter the number").split(",")]
print(i)

enter the number 1,2,3

[1, 2, 3]

In [2]:
i=int(input("enter the no.1:"))
i1=int(input("enter the no.2:"))
p=i*i1
print(p)

enter the no.1: 2
enter the no.2: 3

6

In [5]:
values=input("neter value").split()
print(values)

neter value sumayya kounain yes

['sumayya', 'kounain', 'yes']

In [5]:
values=input("neter value").split(",")
print(values)

neter value 1,2,3

['1', '2', '3']

In [10]:
english=input("enter the sentence")
vowels="aeiou"
count=sum(1 for text in english if text.lower()in vowels)
print("the nuber of vowels",count)

enter the sentence SUMAYYA

the nuber of vowels 3

In [13]:
i=int(input("enter the number"))
if i>=18:
    print("yes")
else:
    print("no")

enter the number 15

no

In [15]:
x=6
r=x%2
if r==0:
    print("even number")
    if x>5:
        print("greater number")
else:
    print("odd number")

even number
greater number

In [2]:
i=1
while i in range (1,5):
    print("data",end=" ")
    j=1
    while j<=4:
        print("science",end=" ")
        j=j+1
    i=i+1
    print()

data science science science science
data science science science science
data science science science science
data science science science science

In [3]:
l=[1,2,3]
for i in l:
    print(i)

1
2
3

In [4]:
for i in range(5):
    print(i)

0
1
2
3
4

In [5]:
for i in range(0,10,5):
    print(i)

0
5

In [6]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50

In [8]:
for i in range(1,51):
    if i%5==0:
        print(i)
        continue

5
10
15
20
25
30
35
40
45
50

In [2]:
for i in range(1,11):
    if i==6:
        break
    print(i)

1
2
3
4
5

In [3]:
for i in range(5):
    print(i)

0
1
2
3
4

In [7]:
for i in range(5):
    print(i)
    continue

0
1
2
3
4

In [8]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50

In [12]:
for i in range(1,5):
    if i==3:
        break
    print("hello",i)

hello 1
hello 2

In [13]:
for i in range(1,5):
    if i==3:
        continue
    print("hello",i)

hello 1
hello 2
hello 4

In [15]:
for i in range(1,5)

SyntaxError: expected ':' (4190323218.py, line 1)

In [16]:
for i in range(1,5):
    pass

In [20]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49

In [27]:
for i in range(1,5):
    i=i+1
    print("####")

####
####
####
####

In [34]:
for i in range(4):
   for j in range(i+1):
    print("#",end=" ")
   print()

#
# #
# # #
# # # #

In [38]:
for i in range(4):
    for j in range(i+1):
        print("#",end=" ")
    print()

#
# #
# # #
# # # #

In [39]:
for i in range(4):
    for j in range(4-i):
        print("#",end=" ")
    print()

# # # #
# # #
# #
#

In [41]:
nums=[12,15,18,21,26]
for num in nums:
    if num%5!=0:
        print(num)

12
18
21
26

In [44]:
nums=[12,18,21,26]
for num in nums:
    if num%5==0:
        print(num)
        break
else:
        print("num not found")

num not found

In [49]:
num=13
for i in range(2,num):
    if num%i==0:
        print("NO")
        break
else:
        print("yes")

yes

In [50]:
for i in range(5):
    print(i)

0
1
2
3
4

In [51]:
l=[1,2,3,4]
for i in l:
    print(i)

1
2
3
4

In [52]:
s="mit"
for s in l:
    print(s)

1
2
3
4

In [60]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50

In [66]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49

In [67]:
for i in range(1,5):
    if i==4:
        break
    print(i)

1
2
3

In [69]:
for i in range(1,7):
    if i==4:
        continue
    print(i)

1
2
3
5
6

In [70]:
import numpy as np

In [71]:
np.__version__

'2.4.6'

In [73]:
l=[1,2,3]
ab=np.array(l)
ab

array([1, 2, 3])

In [74]:
type(ab)

numpy.ndarray

In [75]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [76]:
np.arange(1,5,10)

array([1])

In [78]:
for i in range(5):
    for j in range(i+1):
        print("#",end=" ")
    print()

#
# #
# # #
# # # #
# # # # #

In [79]:
for i in range(4):
    i=i+1
    print("####")

####
####
####
####

In [80]:
for i in range(4):
    if i<=4:
        print("####")

####
####
####
####

In [81]:
for i in range(5):
    for j in range(5-i):
        print("#",end=" ")
    print()

# # # # #
# # # #
# # #
# #
#

In [82]:
l=[1,2,3]
ab=np.array(l)
ab

array([1, 2, 3])

In [83]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [84]:
l=[1,20,3,50]
for i in l:
    if i%5==0:
        print(i)

20
50

In [86]:
l=[1,8,3,7]
for i in l:
    if i%5==0:
        print(i)
    else:
        print("end")

end
end
end
end

In [88]:
l=[1,8,3,7]
for i in l:
    if i%5==0:
        print(i)
else:
    print("end")

end

In [96]:
num=7
for i in range(2,num):
    if num%i==0:
        print("Number is not a prime")
        break
else:
    print("Number is prime")

Number is prime

In [103]:
i=1
while i<=4:
    print("data")
    i=i+1

data
data
data
data

In [1]:
i=1
while i<=4:
    print("data",end="-")
    j=1
    while j<=3:
        print("science",end="-")
        j=j+1
    i=i+1
    print()

data-science-science-science-
data-science-science-science-
data-science-science-science-
data-science-science-science-

In [5]:
x=3
r=x%2
if r==0:
    print("number is even")
else:
    print("number is odd")

number is odd

In [9]:
x=6
r=x%2
if r==0:
    print("number is even")
    if x<=5:
        print("the number is less")
    else:
        print("nmber is greater")       
else:
    print("number is odd")

number is even
nmber is greater

In [11]:
for i in range(4):
    for j in range(i+1):
        print("#",end=" ")
    print()

#
# #
# # #
# # # #

In [12]:
for i in range(4):
    for j in range(4-i):
        print("#",end=" ")
    print()

# # # #
# # #
# #
#

In [2]:
i=1
while i in range(5):
    print("data")
    i=i+1

data
data
data
data

In [6]:
i=1
while i in range(5):
    print("data",end="-")
    j=1
    while j in range(4):
        print("science",end="-")
        j=j+1
    i=i+1
    print()

data-science-science-science-
data-science-science-science-
data-science-science-science-
data-science-science-science-

In [9]:
for i in range(5):
    for j in range(i+1):
        print("*",end=" ")
    print()

*
* *
* * *
* * * *
* * * * *

In [11]:
i=input('enter the word')
if i==i[::-1]:
    print('The no. is pallindrome')
else:
    print('The no. is not a pallindrome')

enter the word sumayyajjjsdj

The no. is not a pallindrome

In [14]:
num=2
r=num%2
if r==0:
    print("The number is even")
else:
    print("The number is odd")

The number is even

In [18]:
num=2
r=num%2
if r==0:
    print("The number is even")
else:
    print('the no,')

The number is even

In [20]:
num=6
r=num%2
if r==0:
    print("The number is even")
    if num<=5:
        print('the no is lesee')
    else:
        print('the no is gretaer')
else:
    print("The number is odd")

The number is even
the no is gretaer

In [23]:
num=3
if num==1:
    print('one')
elif num==2:
    print('two')
else:
    print('no. not found')

no. not found

In [24]:
import numpy as np

In [25]:
np.__version__

'2.4.6'

In [26]:
l=[1,2,3]
ab=np.array(l)
ab

array([1, 2, 3])

In [27]:
type(ab)

numpy.ndarray

In [28]:
np.arange(10,5)

array([], dtype=int64)

In [29]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [30]:
np.arange(5,10,2)

array([5, 7, 9])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [34]:
np.zeros(4,dtype=str)

array(['', '', '', ''], dtype='<U1')

In [35]:
np.ones(2)

array([1., 1.])

In [36]:
np.ones((2),dtype=int)

array([1, 1])

In [37]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
rand(2)

NameError: name 'rand' is not defined

In [39]:
random.rand(2)

NameError: name 'random' is not defined

In [40]:
np.random.rand(2)

array([0.70693202, 0.74234787])

In [42]:
np.random.randint(2)

1

In [46]:
np.random.randint(2,5)

3

In [47]:
np.random.randint(10,10)

ValueError: low >= high

In [50]:
np.random.randint(2,3,(10,10))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)

In [52]:
ab=np.random.randint(2,3,(10,10))
print(ab)

[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]

In [53]:
import numpy as np

In [54]:
np.__version__

'2.4.6'

In [55]:
l=[1,2,3]
print(type(l))

<class 'list'>

In [56]:
ab=np.array(l)
ab

array([1, 2, 3])

In [57]:
type(ab)

numpy.ndarray

In [58]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [59]:
np.arange(5,10,2)

array([5, 7, 9])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [70]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [72]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [73]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [78]:
np.random.randint(5,10,(5,5))

array([[7, 9, 5, 9, 6],
       [5, 7, 6, 7, 6],
       [6, 7, 5, 5, 6],
       [7, 5, 7, 8, 9],
       [8, 6, 6, 7, 9]], dtype=int32)

In [79]:
arr1=np.random.randint(5,10,(5,5))
print(arr1)

[[8 8 5 9 5]
 [9 5 9 7 6]
 [7 9 6 9 5]
 [9 7 6 8 5]
 [8 7 9 5 9]]

In [80]:
print(arr1[:])

[[8 8 5 9 5]
 [9 5 9 7 6]
 [7 9 6 9 5]
 [9 7 6 8 5]
 [8 7 9 5 9]]

In [81]:
print(arr1[::-1])

[[8 7 9 5 9]
 [9 7 6 8 5]
 [7 9 6 9 5]
 [9 5 9 7 6]
 [8 8 5 9 5]]

In [82]:
print(arr1[:])

[[8 8 5 9 5]
 [9 5 9 7 6]
 [7 9 6 9 5]
 [9 7 6 8 5]
 [8 7 9 5 9]]

In [83]:
print(arr1[::3])

[[8 8 5 9 5]
 [9 7 6 8 5]]

In [84]:
print(arr1[-3:-1])

[[7 9 6 9 5]
 [9 7 6 8 5]]

In [85]:
print(arr1[-4:-1])

[[9 5 9 7 6]
 [7 9 6 9 5]
 [9 7 6 8 5]]

In [86]:
print(arr1[2,3])

9

In [87]:
print(arr1[-1:-4])

[]

In [88]:
arr1

array([[8, 8, 5, 9, 5],
       [9, 5, 9, 7, 6],
       [7, 9, 6, 9, 5],
       [9, 7, 6, 8, 5],
       [8, 7, 9, 5, 9]], dtype=int32)

In [96]:
print(arr1[2:5,3:5])

[[9 5]
 [8 5]
 [5 9]]

In [97]:
arr1[2:5]

array([[7, 9, 6, 9, 5],
       [9, 7, 6, 8, 5],
       [8, 7, 9, 5, 9]], dtype=int32)

In [100]:
arr1

array([[8, 8, 5, 9, 5],
       [9, 5, 9, 7, 6],
       [7, 9, 6, 9, 5],
       [9, 7, 6, 8, 5],
       [8, 7, 9, 5, 9]], dtype=int32)

In [99]:
arr1[0,1]

np.int32(8)

In [101]:
arr1[0,1]=10

In [102]:
arr1

array([[ 8, 10,  5,  9,  5],
       [ 9,  5,  9,  7,  6],
       [ 7,  9,  6,  9,  5],
       [ 9,  7,  6,  8,  5],
       [ 8,  7,  9,  5,  9]], dtype=int32)

In [103]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [109]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
np.random.rand(2)

array([0.50008934, 0.76092186])

In [114]:
np.random.rand(2,3)

array([[0.96491812, 0.20159069, 0.62894485],
       [0.21309561, 0.47663833, 0.03486913]])

In [117]:
np.random.randint(2,4,(10,10))

array([[2, 3, 3, 2, 2, 3, 3, 3, 3, 3],
       [2, 3, 2, 2, 3, 3, 2, 3, 3, 2],
       [2, 2, 2, 2, 2, 3, 2, 2, 2, 2],
       [3, 3, 3, 2, 2, 2, 3, 2, 2, 2],
       [3, 3, 3, 3, 2, 2, 2, 2, 2, 3],
       [3, 2, 3, 3, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 3, 3, 2, 3, 2, 3, 2],
       [3, 2, 2, 3, 2, 3, 3, 2, 2, 2],
       [2, 3, 3, 3, 2, 2, 3, 2, 2, 2],
       [3, 2, 2, 2, 3, 2, 3, 3, 3, 2]], dtype=int32)

In [118]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [119]:
arr1

array([[ 8, 10,  5,  9,  5],
       [ 9,  5,  9,  7,  6],
       [ 7,  9,  6,  9,  5],
       [ 9,  7,  6,  8,  5],
       [ 8,  7,  9,  5,  9]], dtype=int32)

In [120]:
arr1[2:4]

array([[7, 9, 6, 9, 5],
       [9, 7, 6, 8, 5]], dtype=int32)

In [121]:
arr1[-3:-2]

array([[7, 9, 6, 9, 5]], dtype=int32)

In [122]:
arr1[-2]

array([9, 7, 6, 8, 5], dtype=int32)

In [123]:
arr1[2,4]

np.int32(5)

In [124]:
print(arr1[2,4])

5

In [126]:
print(arr1[10,4])

IndexError: index 10 is out of bounds for axis 0 with size 5

In [127]:
print(arr1[:,4])

[5 6 5 5 9]

In [129]:
print(arr1[2:4,2:4])

[[6 9]
 [6 8]]

In [131]:
arr1

array([[ 8, 10,  5,  9,  5],
       [ 9,  5,  9,  7,  6],
       [ 7,  9,  6,  9,  5],
       [ 9,  7,  6,  8,  5],
       [ 8,  7,  9,  5,  9]], dtype=int32)

In [130]:
arr1>5

array([[ True,  True, False,  True, False],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False,  True]])

In [132]:
arr1[arr1>5]

array([ 8, 10,  9,  9,  9,  7,  6,  7,  9,  6,  9,  9,  7,  6,  8,  8,  7,
        9,  9], dtype=int32)

In [133]:
np.random.randint(5)

3

In [134]:
arr1

array([[ 8, 10,  5,  9,  5],
       [ 9,  5,  9,  7,  6],
       [ 7,  9,  6,  9,  5],
       [ 9,  7,  6,  8,  5],
       [ 8,  7,  9,  5,  9]], dtype=int32)

In [135]:
arr1[5:2]

array([], shape=(0, 5), dtype=int32)

In [136]:
import numpy as np

In [137]:
np.__version__

'2.4.6'

In [138]:
l=[1,2,3]
type(l)

list

In [139]:
arr=np.array(l)
arr

array([1, 2, 3])

In [140]:
type(arr)

numpy.ndarray

In [141]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [142]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [143]:
np.arange(5,10,2)

array([5, 7, 9])

In [144]:
np.arange(10,10)

array([], dtype=int64)

In [145]:
np.arange(10,5)

array([], dtype=int64)

In [146]:
np.arange(10,5,2)

array([], dtype=int64)

In [147]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [150]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [151]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [153]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [154]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [155]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [156]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [157]:
rand(5)

TypeError: 'int' object is not callable

In [158]:
random.rand(5)

NameError: name 'random' is not defined

In [159]:
np.random.rand(5)

array([0.38529815, 0.18783741, 0.03397231, 0.11495942, 0.05090739])

In [170]:
np.random.randint(5,40,(10,10))

array([[21, 20, 24, 16,  5, 34, 14, 30, 31, 35],
       [35,  9, 26, 28, 27, 33, 14, 37, 33, 13],
       [26, 11, 33, 39,  8,  5, 20,  8, 11, 16],
       [24, 38,  6, 11, 28, 37, 20, 37, 13, 18],
       [ 9, 20, 14, 36,  5, 16, 16, 33, 20, 31],
       [ 6, 31, 28, 35, 30, 24, 33,  6,  9, 18],
       [17, 12, 10, 16, 19,  6, 32,  7, 14, 29],
       [22, 30, 34, 24, 29, 19, 36, 35, 18, 23],
       [23, 19, 15, 14, 22,  9,  7, 17, 21, 14],
       [23,  9, 37, 27, 11, 12, 33,  7,  7, 36]], dtype=int32)

In [171]:
import numpy as np

In [172]:
np.__version__

'2.4.6'

In [173]:
l=[1,2,3,4]
print(type(l))

<class 'list'>

In [174]:
ab=np.array(l)
ab

array([1, 2, 3, 4])

In [175]:
type(ab)

numpy.ndarray

In [177]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [178]:
np.arange(5,2)

array([], dtype=int64)

In [179]:
np.arange(2,5)

array([2, 3, 4])

In [180]:
np.arange(2,5,2)

array([2, 4])

In [181]:
np.arange(20,10)

array([], dtype=int64)

In [182]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [184]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [187]:
np.zeros((5),dtype=int)

array([0, 0, 0, 0, 0])

In [188]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [189]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [191]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [192]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [193]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [194]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [196]:
np.ones((6,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [198]:
np.twos((6))

AttributeError: module 'numpy' has no attribute 'twos'

In [199]:
rand(5)

TypeError: 'int' object is not callable

In [200]:
random.rand(6)

NameError: name 'random' is not defined

In [201]:
np.random.rand(5)

array([0.66642311, 0.39603501, 0.60297531, 0.42184711, 0.70602377])

In [204]:
np.random.randint(5)

4

In [205]:
np.random.randint(5,10,(5,5))

array([[5, 9, 7, 7, 9],
       [7, 7, 5, 5, 7],
       [6, 6, 9, 7, 6],
       [6, 8, 6, 8, 5],
       [5, 8, 8, 5, 9]], dtype=int32)

In [207]:
arr1=np.random.randint(5,10,(5,5))
print(arr1)

[[6 8 5 9 7]
 [9 5 7 5 6]
 [5 5 7 9 5]
 [5 8 6 7 8]
 [5 7 9 9 6]]

In [208]:
arr1[2]

array([5, 5, 7, 9, 5], dtype=int32)

In [209]:
arr1[-1]

array([5, 7, 9, 9, 6], dtype=int32)

In [210]:
arr1[::-1]

array([[5, 7, 9, 9, 6],
       [5, 8, 6, 7, 8],
       [5, 5, 7, 9, 5],
       [9, 5, 7, 5, 6],
       [6, 8, 5, 9, 7]], dtype=int32)

In [211]:
arr1[::3]

array([[6, 8, 5, 9, 7],
       [5, 8, 6, 7, 8]], dtype=int32)

In [212]:
arr1[::-2]

array([[5, 7, 9, 9, 6],
       [5, 5, 7, 9, 5],
       [6, 8, 5, 9, 7]], dtype=int32)

In [213]:
arr1

array([[6, 8, 5, 9, 7],
       [9, 5, 7, 5, 6],
       [5, 5, 7, 9, 5],
       [5, 8, 6, 7, 8],
       [5, 7, 9, 9, 6]], dtype=int32)

In [214]:
arr1[0:2]

array([[6, 8, 5, 9, 7],
       [9, 5, 7, 5, 6]], dtype=int32)

In [215]:
arr1[2]

array([5, 5, 7, 9, 5], dtype=int32)

In [216]:
arr1[2,3]

np.int32(9)

In [217]:
arr1[0,1]

np.int32(8)

In [218]:
arr1[0,1]=10

In [219]:
arr1

array([[ 6, 10,  5,  9,  7],
       [ 9,  5,  7,  5,  6],
       [ 5,  5,  7,  9,  5],
       [ 5,  8,  6,  7,  8],
       [ 5,  7,  9,  9,  6]], dtype=int32)

In [220]:
arr1[:,3]

array([9, 5, 9, 7, 9], dtype=int32)

In [221]:
arr1[2:3,3:4]

array([[9]], dtype=int32)

In [222]:
arr1[2:4,3:5]

array([[9, 5],
       [7, 8]], dtype=int32)

In [224]:
arr1[arr1>5]

array([ 6, 10,  9,  7,  9,  7,  6,  7,  9,  8,  6,  7,  8,  7,  9,  9,  6],
      dtype=int32)

In [225]:
arr1>5

array([[ True,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [False, False,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [226]:
arr1[arr1>=5]

array([ 6, 10,  5,  9,  7,  9,  5,  7,  5,  6,  5,  5,  7,  9,  5,  5,  8,
        6,  7,  8,  5,  7,  9,  9,  6], dtype=int32)

In [227]:
arr1[arr1==5]

array([5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [228]:
arr1[arr1!=5]

array([ 6, 10,  9,  7,  9,  7,  6,  7,  9,  8,  6,  7,  8,  7,  9,  9,  6],
      dtype=int32)

In [229]:
arr1

array([[ 6, 10,  5,  9,  7],
       [ 9,  5,  7,  5,  6],
       [ 5,  5,  7,  9,  5],
       [ 5,  8,  6,  7,  8],
       [ 5,  7,  9,  9,  6]], dtype=int32)

In [230]:
arr1.reshape(5,5)

array([[ 6, 10,  5,  9,  7],
       [ 9,  5,  7,  5,  6],
       [ 5,  5,  7,  9,  5],
       [ 5,  8,  6,  7,  8],
       [ 5,  7,  9,  9,  6]], dtype=int32)

In [232]:
arr1.reshape(25,1)

array([[ 6],
       [10],
       [ 5],
       [ 9],
       [ 7],
       [ 9],
       [ 5],
       [ 7],
       [ 5],
       [ 6],
       [ 5],
       [ 5],
       [ 7],
       [ 9],
       [ 5],
       [ 5],
       [ 8],
       [ 6],
       [ 7],
       [ 8],
       [ 5],
       [ 7],
       [ 9],
       [ 9],
       [ 6]], dtype=int32)

In [233]:
arr1

array([[ 6, 10,  5,  9,  7],
       [ 9,  5,  7,  5,  6],
       [ 5,  5,  7,  9,  5],
       [ 5,  8,  6,  7,  8],
       [ 5,  7,  9,  9,  6]], dtype=int32)

In [234]:
arr1.max()

np.int32(10)

In [235]:
arr1.min()

np.int32(5)

In [1]:
i=1
while i in range(0,5):
    print("data")
    i=i+1

data
data
data
data

In [3]:
i=1
while i<=5:
    print("data",end="-")
    j=1
    while j<=4:
        print("science",end="-")
        j=j+1
    i=i+1
    print()

data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-
data-science-science-science-science-

In [4]:
l=[1,2,3]
for i in l:
    print(i)

1
2
3

In [6]:
s='nit'
for i in s:
    print(i)

n
i
t

In [9]:
x=6
for i in range(2,x):
    if x%i==0:
        print("The number is not a prime")
        break
else:
    print("The number is prime")

The number is not a prime

In [11]:

for i in range(0,5):
    print(i)

0
1
2
3
4

In [3]:
for i in range(1,51):
    if i%5==0:
        print(i)
        i=i+1

5
10
15
20
25
30
35
40
45
50

In [4]:
for i in range(1,51):
    if i%5!=0:
        print(i)
        i=i+1

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49

In [15]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49

In [16]:
for i in range(1,51):
    if i==3:
        break
    print(i)

1
2

In [17]:
for i in range(1,51)

SyntaxError: expected ':' (2346021345.py, line 1)

In [18]:
for i in range(1,51):
    pass

In [45]:
x=3
r=x%2
if r==0:
print("The number is even")
else:
    print("The number is odd")

IndentationError: expected an indented block after 'if' statement on line 3 (1608059494.py, line 4)

In [24]:
x=19
if x<=18:
    print('YOU are eligible for vote')
else:
    print('you are not eligible for vote')

you are not eligible for vote

In [29]:
x=4
r=x%2
if r==0:
    print("The number is even")
    if x<=5:
        print("the no. is less")
    else:
        print("The n. is greter")
else:
    print("The number is odd")

The number is even
the no. is less

In [34]:
x=3
if x==1:
    print("one")
elif x==2:
    print("two")
else:
    print("no. not found")

no. not found

In [35]:
range(5)

range(0, 5)

In [36]:
list(range(5))

[0, 1, 2, 3, 4]

In [37]:
list(range(5,10,2))

[5, 7, 9]

In [38]:
list(range(5,10,2,3))

TypeError: range expected at most 3 arguments, got 4

In [40]:
l=[1,2,3,7,6,5]
print(l)

[1, 2, 3, 7, 6, 5]

In [41]:
s={1,2,3,7,6,5}
print(s)

{1, 2, 3, 5, 6, 7}

In [46]:
2 ** 3 ** 2

512

In [47]:
-5 // 2

-3

In [48]:
1 < x < 5

True

In [49]:
5=+5

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (2192946551.py, line 1)

In [50]:
5+=5

SyntaxError: 'literal' is an illegal expression for augmented assignment (422671266.py, line 1)

In [51]:
x=2
x+=2

In [52]:
x

4

In [57]:
x=2
x=+=2

SyntaxError: invalid syntax (441152509.py, line 2)

In [58]:
x

2

In [59]:
s={}
type(s)

dict

In [63]:
b={1:2}
type(b)

dict

In [62]:
s=dict()
type(s)

dict

In [66]:
d={1:"Apple",2:"banana",3:"cherry"}
d

{1: 'Apple', 2: 'banana', 3: 'cherry'}

In [ ]:
d={1:"Apple",2:("banana"),3:"cherry"}
d

In [67]:
x=input("Enter the space separated value").split()
x

Enter the space separated value 1 2 3

['1', '2', '3']

In [69]:
x=int(input("Enter the number"))
if x>0:
    print("The number is positive")
else:
    print("The number is negative")

Enter the number -1

The number is negative

In [77]:
text=input("Enter the word")
vowels="aeiou"
count=sum(1 for char in text if char.lower() in vowels)
print(count)

Enter the word sumayya

3

In [79]:
x=int(input("Enter the number"))
for i in range(2,x):
    if x%i==0:
        print("The number is not a prime")
        break
else:
    print("The number is prime")

Enter the number 4

The number is not a prime

In [80]:
x=input("Enter True or False")
x

Enter True or False True

'True'

In [83]:
user_input = input("Enter True or False: ").lower() == "true"

Enter True or False:  true

In [85]:
x=int(input("Enter the number"))
f=1
for i in range(1,x+1):
    f=f*i
print(f)

Enter the number 5

120

In [86]:
x=int(input("ener the number"))
f=1
for i in range(1,x+1):
    f=f*i
print(f)

ener the number 5

120

In [94]:
user_input = input("Enter something: ").strip()
if not user_input: 
       print("Input cannot be empty.") 
else: 
       print(f"You entered: {user_input}")

Enter something:

Input cannot be empty.

In [91]:
import math 
num = int(input("Enter a number: ")) 
if math.isqrt(num) ** 2 == num: 
       print("Perfect square") 
else: 
       print("Not a perfect square")

Enter a number:  4

Perfect square

In [98]:
import math
x=int(input("Enter the number"))
if math.sqrt(x) **2==x:
    print("the no. is perfect square")
else:
    print("The no. is not")

Enter the number 4

the no. is perfect square

In [101]:
python 
try: 
    num = int(input("Enter a number: ")) 
except ValueError: 
       print("Invalid input! Please enter a valid integer.")

NameError: name 'python' is not defined

In [103]:
a=input("Enter the name")
b=input("enter the address")
print(a.count(b))

Enter the name thanks
enter the address welcome

0

In [104]:
text = input("Enter a string: ") 
char = input("Enter a character to count: ") 
print(f"Occurrence of {char}: {text.count(char)}")

Enter a string:  sumayya
Enter a character to count:  sumayya

Occurrence of sumayya: 1

In [106]:
a=input("Enter the sentence").split()
print(len(a))

Enter the sentence sumayya kounain

2

In [108]:
a=input("enter the string")
for i in a:
    if i.isdigit():
        print(i)

enter the string 1 2 3 4

1
2
3
4

In [109]:
numbers = list(map(int, input("Enter numbers separated by spaces: ").split())) 
print("Maximum number:", max(numbers))

Enter numbers separated by spaces:  1 456 23 4

Maximum number: 456

In [111]:
l=int(input("Enter the numbers:"))
print(max(l))

Enter the numbers: 1 2 34 5

ValueError: invalid literal for int() with base 10: '1 2 34 5'

In [115]:
l=list(map(int,input("enter the numbers").split()))
print(max(l))

enter the numbers 1 23 5

23

In [ ]:
x=int(input("enter the numbers"))
f=1
for i in range(1,x+1):
    f=f*i
print(f)

In [2]:
x=10
y=3.0
z=x/y
print(type(z).__name__)

float

In [3]:
x=10
y=x
x=20
print(y)

10

In [5]:
x=10
y=10.0
print(x==y)
print(type(x)==type(y))

True
False

In [6]:
data=[10,20,30]
data.append([40,50])
data.extend([60,70])
print(data)

[10, 20, 30, [40, 50], 60, 70]

In [7]:
text="Data science"
result=text[::2]
print(result)

Dt cec

In [8]:
student={
    "name":"Rahul",
    "age":22,
    "course":"Data science"
}
result=student.get("marks",75)
print(result)

75

In [10]:
x=12
y=8
z=15
if x>y and z>x:
    result="A"
elif x>y or z<y:
    result="B"
else:
    result="c"
print(result)

A

In [11]:
def calculate(n):
    if n<=1:
        return 1
    return n+calculate(n-2)
result=calculate(5)
print(result)

9

In [12]:
num=121
reverse=0
temp=num
while temp>0:
    digit=temp%10
    reverse=reverse*10+digit
    temp//=10
if num==reverse:
    result="palindrome"
else:
    result="not palindrome"
print(result)

palindrome

In [13]:
total=0
for i in range(1,6):
    if i%2==0:
        continue
    total+=i
print(total)

9

In [14]:
n=5
result=1
while n>1:
    result*=n
    n-=2
print(result)

15

In [15]:
import numpy as np
arr=np.arange(1,13)
result=arr.reshape(3,4)
print(result[1:,1:3])

[[ 6  7]
 [10 11]]

In [16]:
import numpy as np
a=np.ones((2,3))
b=np.zeros((2,3))
result=a+b
print(result)

[[1. 1. 1.]
 [1. 1. 1.]]

In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result=np.sum(arr,axis=0)
print(result)

[5 7 9]

In [18]:
n=6
result=0
for i in range(1,n+1):
    if n%i==0:
        result+=i
print(result)

12

In [19]:
number=12345
total=0
while number>0:
    digit=number%10
    if digit%2!=0:
        total+=digit
    number//=10
print(total)

9

In [21]:
text="PYTHON"
result=""
for i,ch in enumerate(text):
    if i%2==0:
        result+=ch.lower()
    else:
        result+=ch
print(result)

pYtHoN

In [23]:
marks={
    "Python":78,
    "SQL":85,
    "Statistics":62,
    "Machine Learning":91
}
count=0
for subject,mark in marks.items():
    if mark >=80:
        count+=1
    elif mark>=60:
        count+=0.5
print(count)

3.0

In [24]:
2 & 1

0

In [26]:
c="data"

In [27]:
a in c

TypeError: 'in <string>' requires string as left operand, not numpy.ndarray

In [28]:
b=range(10)

In [29]:
5 in b

True

In [30]:
l=[1,2,3]

In [31]:
3 in l

True

In [36]:
t1=["x","y"]

In [38]:
"x" in t1

True

In [39]:
~1

-2

In [40]:
None is None

True

In [41]:
[] is []

False

In [42]:
True is True

True

In [44]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4124\1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5

True

In [45]:
print(x) if x>0 else None

12

In [51]:
import pandas as pd

In [52]:
pd.__version__

'3.0.3'

In [53]:
df=pd.read_excel(r"C:\Users\LENOVO\Downloads\data.xlsx")

In [54]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [76]:
type(df)

pandas.DataFrame

In [55]:
type(df)

pandas.DataFrame

In [59]:
df.shape

(195, 5)

In [58]:
len(df)

195

In [60]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [61]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [62]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [63]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [64]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [65]:
df_cat=df[['CountryName','CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [66]:
len(df_cat)

195

In [68]:
df_cat.shape

(195, 3)

In [69]:
df_num=df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [70]:
len(df_num)

195

In [71]:
df_num.shape

(195, 2)

In [72]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [73]:
df_num.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BirthRate      195 non-null    float64
 1   InternetUsers  195 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB

In [77]:
121%10

1

In [78]:
12345%10

5

In [80]:
1%2

1

In [81]:
1//10for i in range(3):
    print(i)

0

In [79]:
12345//10

1234

In [83]:
x = [1, 2, 3]
x.append([4, 5])
print(len(x))
print(x)

4
[1, 2, 3, [4, 5]]

In [84]:
for i in range(3):
    print(i)

0
1
2

In [85]:
print(bool([]), bool([0]), bool(""), bool(" "))

False True False True

In [86]:
import pandas as pd

In [87]:
pd.__version__

'3.0.3'

In [88]:
emp=pd.read_excel(r"C:\Users\LENOVO\Downloads\Rawdata.xlsx")

In [89]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [90]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [91]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [92]:
emp.head(1)

   Name         Domain       Age Location  Salary Exp
0  Mike  Datascience#$  34 years   Mumbai  5^00#0  2+

In [93]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: str

In [95]:
emp['Name']=emp['Name'].str.replace(r'\W','',regex=True)

In [96]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: str

In [97]:
emp.head(1)

   Name         Domain       Age Location  Salary Exp
0  Mike  Datascience#$  34 years   Mumbai  5^00#0  2+

In [98]:
emp['Domain']=emp['Domain'].str.replace(r'\W','',regex=True)

In [99]:
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: str

In [100]:
emp['Age']=emp['Age'].str.replace(r'\W','',regex=True)

In [101]:
emp['Age']

0    34years
1       45yr
2        NaN
3        NaN
4       67yr
5       55yr
Name: Age, dtype: str

In [103]:
emp['Age']=emp['Age'].str.extract('(\d+)')

In [104]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: str

In [105]:
emp.head()

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year

In [106]:
emp['Salary']=emp['Salary'].str.replace(r'\W','',regex=True)

In [107]:
emp['Salary']

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: str

In [108]:
emp['Exp']=emp['Exp'].str.replace(r'\W','',regex=True)

In [109]:
emp['Exp']

0        2
1        3
2     4yrs
3      NaN
4    5year
5       10
Name: Exp, dtype: str

In [110]:
emp['Exp']=emp['Exp'].str.extract('(\d+)')

In [111]:
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: str

In [112]:
emp.head()

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5

In [113]:
cust_emp=emp.copy()

In [114]:
cust_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [115]:
import numpy as np

In [118]:
cust_emp['Age']=cust_emp['Age'].fillna(np.mean(pd.to_numeric(cust_emp['Age'])))

In [119]:
cust_emp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  NaN
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [122]:
cust_emp['Exp']=cust_emp['Exp'].fillna(np.mean(pd.to_numeric(cust_emp['Exp'])))

In [123]:
cust_emp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [126]:
cust_emp['Location']=cust_emp['Location'].fillna(cust_emp['Location'].mode()[0])

In [127]:
cust_emp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10